# Generated by Django 5.1 on 2024-09-07 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_order_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
